import { Exercise } from "@/types/routine";

export const ejerciciosPreestablecidos = {
  Pecho: [
    "Press de Banca con Barra",
    "Press de Banca con Mancuernas",
    "Press de Banca Inclinado",
    "Press de Banca Declinado",
    "Aperturas con Mancuernas",
    "Aperturas en Máquina",
    "Aperturas en Cable",
    "Fondos en Paralelas",
    "Press de Banca Smith",
    "Cruces en Cable",
    "Flexiones",
    "Flexiones Diamante",
    "Flexiones Explosivas",
    "Press de Banca con Grip Cerrado",
    "Pullover con Mancuerna",
    "Press de Banca con Banda Elástica",
    "Flexiones con Palmada",
    "Press de Banca con Pausa",
    "Aperturas en Banco Inclinado",
    "Press de Banca con Rotación"
  ],
  Espalda: [
    "Dominadas",
    "Remo con Barra",
    "Remo con Mancuernas",
    "Remo en Máquina",
    "Remo en Cable",
    "Peso Muerto",
    "Peso Muerto Rumano",
    "Pull-ups",
    "Chin-ups",
    "Remo T",
    "Remo Invertido",
    "Superman",
    "Extensión de Espalda",
    "Remo con Banda Elástica",
    "Pull-down",
    "Pull-down Cerrado",
    "Pull-down Ancho",
    "Remo Sentado",
    "Remo Unilateral",
    "Pull-down Unilateral"
  ],
  Piernas: [
    "Sentadillas",
    "Sentadillas Frontales",
    "Sentadillas Búlgaras",
    "Prensa de Piernas",
    "Extensiones de Cuádriceps",
    "Curl de Femoral",
    "Elevación de Talones",
    "Zancadas",
    "Zancadas con Mancuernas",
    "Zancadas con Barra",
    "Peso Muerto Rumano",
    "Hip Thrust",
    "Sentadillas Sumo",
    "Sentadillas Hack",
    "Curl de Piernas",
    "Extensión de Pantorrillas",
    "Sentadillas con Salto",
    "Pistol Squats",
    "Leg Press",
    "Caminata del Granjero"
  ],
  Hombros: [
    "Press Militar",
    "Press Arnold",
    "Elevaciones Laterales",
    "Elevaciones Frontales",
    "Face Pull",
    "Rotaciones Externas",
    "Rotaciones Internas",
    "Press con Mancuernas",
    "Press en Máquina",
    "Shrugs",
    "Upright Row",
    "Lateral Raises",
    "Front Raises",
    "Rear Delt Fly",
    "Cable Lateral Raises",
    "Press Behind Neck",
    "Clean and Press",
    "Military Press",
    "Seated Dumbbell Press",
    "Standing Dumbbell Press"
  ],
  Bíceps: [
    "Curl de Bíceps con Barra",
    "Curl de Bíceps con Mancuernas",
    "Curl de Bíceps en Cable",
    "Curl de Bíceps en Máquina",
    "Curl de Bíceps con Banda Elástica",
    "Curl de Bíceps Martillo",
    "Curl de Bíceps Inclinado",
    "Curl de Bíceps Concentrado",
    "Curl de Bíceps Spider",
    "Curl de Bíceps Preacher",
    "Curl de Bíceps Zottman",
    "Curl de Bíceps Cross Body",
    "Curl de Bíceps con Rotación",
    "Curl de Bíceps 21s",
    "Curl de Bíceps con Pausa",
    "Curl de Bíceps con Banda",
    "Curl de Bíceps Unilateral",
    "Curl de Bíceps Alternado",
    "Curl de Bíceps Sentado",
    "Curl de Bíceps de Pie"
  ],
  Tríceps: [
    "Extensiones de Tríceps",
    "Fondos en Paralelas",
    "Press Francés",
    "Extensiones de Tríceps en Cable",
    "Extensiones de Tríceps con Mancuernas",
    "Extensiones de Tríceps en Máquina",
    "Extensiones de Tríceps con Banda Elástica",
    "Extensiones de Tríceps Unilaterales",
    "Extensiones de Tríceps Sentado",
    "Extensiones de Tríceps de Pie",
    "Extensiones de Tríceps Inclinado",
    "Extensiones de Tríceps Declinado",
    "Extensiones de Tríceps con Rotación",
    "Extensiones de Tríceps con Pausa",
    "Extensiones de Tríceps con Banda",
    "Extensiones de Tríceps Unilaterales",
    "Extensiones de Tríceps Alternadas",
    "Extensiones de Tríceps con Barra",
    "Extensiones de Tríceps con Cable Alto",
    "Extensiones de Tríceps con Cable Bajo"
  ],
  Abdomen: [
    "Crunches",
    "Plancha",
    "Plancha Lateral",
    "Elevación de Piernas",
    "Russian Twist",
    "Mountain Climbers",
    "Burpees",
    "Abdominales Bicicleta",
    "Abdominales con Banda",
    "Abdominales con Cable",
    "Abdominales con Pelota",
    "Abdominales con Peso",
    "Abdominales con Rotación",
    "Abdominales con Pausa",
    "Abdominales con Banda",
    "Abdominales Unilaterales",
    "Abdominales Alternados",
    "Abdominales Sentado",
    "Abdominales de Pie",
    "Abdominales con Piernas Elevadas"
  ],
  Antebrazos: [
    "Curl de Muñeca",
    "Curl de Muñeca Inverso",
    "Curl de Muñeca con Barra",
    "Curl de Muñeca con Mancuernas",
    "Curl de Muñeca en Cable",
    "Curl de Muñeca con Banda",
    "Curl de Muñeca Unilateral",
    "Curl de Muñeca Alternado",
    "Curl de Muñeca Sentado",
    "Curl de Muñeca de Pie",
    "Curl de Muñeca Inclinado",
    "Curl de Muñeca Declinado",
    "Curl de Muñeca con Rotación",
    "Curl de Muñeca con Pausa",
    "Curl de Muñeca con Banda",
    "Curl de Muñeca Unilateral",
    "Curl de Muñeca Alternado",
    "Curl de Muñeca Sentado",
    "Curl de Muñeca de Pie",
    "Curl de Muñeca con Peso"
  ],
  Pantorrillas: [
    "Elevación de Talones",
    "Elevación de Talones Sentado",
    "Elevación de Talones de Pie",
    "Elevación de Talones en Máquina",
    "Elevación de Talones con Banda",
    "Elevación de Talones Unilateral",
    "Elevación de Talones Alternado",
    "Elevación de Talones con Peso",
    "Elevación de Talones con Barra",
    "Elevación de Talones con Mancuernas",
    "Elevación de Talones en Escalón",
    "Elevación de Talones Declinado",
    "Elevación de Talones con Rotación",
    "Elevación de Talones con Pausa",
    "Elevación de Talones con Banda",
    "Elevación de Talones Unilateral",
    "Elevación de Talones Alternado",
    "Elevación de Talones Sentado",
    "Elevación de Talones de Pie",
    "Elevación de Talones con Peso"
  ]
};

export const diasSemana = [
  "Lunes",
  "Martes",
  "Miércoles",
  "Jueves",
  "Viernes",
  "Sábado",
  "Domingo"
];

export function getExercisesByDay(exercises: Exercise[]) {
  return exercises.reduce((acc, exercise) => {
    if (!acc[exercise.day]) {
      acc[exercise.day] = [];
    }
    acc[exercise.day].push(exercise);
    return acc;
  }, {} as Record<string, Exercise[]>);
} 